I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1041, in script
    if research(1):
  File "game/script.rpy", line 1041, in <module>
    if research(1):
NameError: name 'research' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1041, in script
    if research(1):
  File "D:\Library\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "D:\Library\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Library\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1041, in <module>
    if research(1):
NameError: name 'research' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Final Project 1.0
Sun Apr 30 18:32:01 2023
